name: Golang Scan

# The scheduled workflow runs every day at 03:00 UTC time.
on:
  schedule:
  - cron: '0 3 * * *'

jobs:
  golang_scan:
    name: Golang Scheduled Scan
    uses: crushten/github_workflow_repo/.github/workflows/go_application_scan.yml@main