name: Scan

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every day at 03:00 UTC time.
on:
  schedule:
  - cron: '0 3 * * *'

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: on
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go version
        uses: actions/setup-go@v3
        with:
          go-version-file: 'application/go.mod'
      - run: go version

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.12.0

      - name: Run gosec
        run: cd application/ && gosec -tests .

      - name: Create Go dep list
        run: cd application/ && go list -json -m all > go.list

      - name: Scan with specific Nancy version
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2
        with:
          nancyVersion: "v1.0.37"
          goListFile: application/go.list